name: ci-cd
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.3', tools: composer:v2, extensions: mbstring, intl, pdo_mysql }
      - run: mkdir -p storage/framework/{cache,sessions,views} bootstrap/cache
      - run: composer validate --no-check-publish
      - run: composer install --no-interaction --prefer-dist --no-scripts
      - run: git ls-files '*.php' | xargs -r -n1 php -l
