name: site-quality
on:
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      BASE: https://swaeduae.ae
    steps:
      - name: Curl core pages
        shell: bash
        run: |
          set -u
          urls=(/ /admin/login /org/login /qr/verify)
          echo "| URL | Status | Note |"
          echo "|-----|--------|------|"
          for U in "${urls[@]}"; do
            CODE=$(curl -sS -o /dev/null -w "%{http_code}" -I --max-time 45 --retry 2 --retry-all-errors "$BASE$U")
            RC=$?
            if [ $RC -ne 0 ]; then
              echo "| $U | curl $RC | WARN |"
            elif [[ "$CODE" =~ ^(200|301|302)$ ]]; then
              echo "| $U | $CODE | OK |"
            else
              echo "| $U | $CODE | WARN |"
            fi
          done

      - name: Lighthouse CI
        run: npx -y @lhci/cli@0.12.x collect --url "$BASE" --quiet
