name: site-quality
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quick curl smoke
        run: |
          PAGES="/ /about /contact /opportunities /organizations /stories /login /register /org/login /org/register /qr/verify /certificates/verify /privacy /terms"
          FAIL=0
          for p in $PAGES; do
            URL="https://www.swaeduae.ae$p"
            CODE=$(curl -s -o /dev/null -w "%{http_code}" -L "$URL" || echo 000)
            HTML=$(curl -s -L "$URL" || true)
            TAILWIND=$(grep -c 'cdn.tailwindcss.com' <<<"$HTML" || true)
            APPCSS=$(grep -cE '/assets/app\.css' <<<"$HTML" || true)
            echo "$p -> code=$CODE tailwind=$TAILWIND app.css=$APPCSS"
            if [ "$CODE" != "200" ] || [ "$TAILWIND" -eq 0 ] || [ "$APPCSS" -eq 0 ]; then
              FAIL=1
            fi
          done
          exit $FAIL
